In [ ]:
pip install selenium

In [5]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument("--start-maximized")  # Opens browser in full screen
chrome_options.add_argument("--disable-blink-features=AutomationControlled")  # Avoids detection

driver = webdriver.Chrome(options=chrome_options)  # Initialize browser
driver.get('https://www.cardekho.com/used-cars+in+bangalore')
time.sleep(5)  # Wait for page to fully load

last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial height

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")  # Scroll to bottom
    time.sleep(5)  # Wait for new data to load

    new_height = driver.execute_script("return document.body.scrollHeight")  # Get new height

    if new_height == last_height:  # If no new content, break loop
        break
    last_height = new_height

cars = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

structured_data = []

for car in cars:
    try:
        details = car.text.split("\n")  # Split details by line breaks
        
        # Extract Year and Car Name
        year_and_name = details[0].split(" ", 1)
        year = year_and_name[0]
        car_name = year_and_name[1] if len(year_and_name) > 1 else "N/A"

        # Extract Mileage, Fuel Type, Transmission
        mileage = fuel_type = transmission = ""
        if len(details) > 1 and "•" in details[1]:
            specs = [x.strip() for x in details[1].split("•")]
            mileage = specs[0].replace("kms", "").strip() if len(specs) > 0 else ""
            fuel_type = specs[1] if len(specs) > 1 else ""
            transmission = specs[2] if len(specs) > 2 else ""

        # Extract Price
        price = details[2].replace("₹", "").replace("Lakh", "").strip() if len(details) > 2 else "N/A"

        # Extract Location
        location = details[-1] if len(details) > 3 else "N/A"

        # Append extracted data
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })

    except Exception as e:
        print(f"Error processing car details: {details}\nError: {e}")

driver.quit()  # Close browser

# Convert to DataFrame
car_df = pd.DataFrame(structured_data)

# Save as CSV
car_df.to_csv('bengalure_car_details.csv', index=False)

# Display DataFrame & Count
print(car_df)

      Year                                    Car Name Mileage (kms)  \
0     2024                     Force Gurkha 2.6 Diesel         2,000
1     2020                Kia Sonet HTX Turbo iMT BSVI        23,589
2     2023          Mercedes-Benz GLS 400d 4MATIC BSVI        15,000
3     2022                       Kia Seltos HTK Diesel        19,116
4     2021  Mercedes-Benz A-Class Limousine A 200 BSVI         6,000
...    ...                                         ...           ...
2375  2016      Mahindra KUV 100 NXT G80 K2 Plus 6 Str        58,052
2376  2015                             Maruti Ciaz VXi        62,333
2377  2023                    Maruti Alto K10 VXI Plus         8,898
2378  2015                    Renault KWID 1.0 RXT Opt        35,742
2379  2014                   Hyundai Verna 1.6 VTVT SX        40,973

     Fuel Type Transmission Price (Lakh)                           Location
0       Diesel       Manual        18.50             Indiranagar, Bangalore
1       Petrol       Manual         8.38                   Hoodi, Bangalore
2       Diesel    Automatic   1.29 Crore                Nagavara, Bangalore
3       Diesel       Manual        11.44                  Jakkur, Bangalore
4       Petrol    Automatic        48.95             Indiranagar, Bangalore
...        ...          ...          ...                                ...
2375    Petrol       Manual         3.78             Malleswaram, Bangalore
2376    Petrol       Manual         4.99  Kengiri Satellite Town, Bangalore
2377    Petrol       Manual         5.19              Btm Layout, Bangalore
2378    Petrol       Manual         2.75             Malleswaram, Bangalore
2379    Petrol       Manual         4.98          Samethanahalli, Bangalore

[2380 rows x 7 columns]

In [ ]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument("--start-maximized")  # Opens browser in full screen
chrome_options.add_argument("--disable-blink-features=AutomationControlled")  # Avoids detection

driver = webdriver.Chrome(options=chrome_options)  # Initialize browser
driver.get('https://www.cardekho.com/used-cars+in+Chennai')
time.sleep(5)  # Wait for page to fully load

last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial height

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")  # Scroll to bottom
    time.sleep(5)  # Wait for new data to load

    new_height = driver.execute_script("return document.body.scrollHeight")  # Get new height

    if new_height == last_height:  # If no new content, break loop
        break
    last_height = new_height

cars = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

structured_data = []

for car in cars:
    try:
        details = car.text.split("\n")  # Split details by line breaks
        
        # Extract Year and Car Name
        year_and_name = details[0].split(" ", 1)
        year = year_and_name[0]
        car_name = year_and_name[1] if len(year_and_name) > 1 else "N/A"

        # Extract Mileage, Fuel Type, Transmission
        mileage = fuel_type = transmission = ""
        if len(details) > 1 and "•" in details[1]:
            specs = [x.strip() for x in details[1].split("•")]
            mileage = specs[0].replace("kms", "").strip() if len(specs) > 0 else ""
            fuel_type = specs[1] if len(specs) > 1 else ""
            transmission = specs[2] if len(specs) > 2 else ""

        # Extract Price
        price = details[2].replace("₹", "").replace("Lakh", "").strip() if len(details) > 2 else "N/A"

        # Extract Location
        location = details[-1] if len(details) > 3 else "N/A"

        # Append extracted data
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })

    except Exception as e:
        print(f"Error processing car details: {details}\nError: {e}")

driver.quit()  # Close browser

# Convert to DataFrame
car_df = pd.DataFrame(structured_data)

# Save as CSV
car_df.to_csv('Chennai_car_details.csv', index=False)

# Display DataFrame & Count
print(car_df)

      Year                                  Car Name Mileage (kms) Fuel Type  \
0     2018          Hyundai Grand i10 1.2 Kappa Asta        32,000    Petrol
1     2023            Mercedes-Benz GLA 220d 4M BSVI         5,000    Diesel
2     2022             Renault KWID 1.0 RXT AMT BSVI        13,119    Petrol
3     2022                 Tata Punch Adventure BSVI        32,148    Petrol
4     2018                 Honda Amaze VX CVT i-VTEC        70,000    Petrol
...    ...                                       ...           ...       ...
1164  2015                    Audi A6 35 TDI Premium        70,500    Diesel
1165  2017               Audi A3 35 TDI Premium Plus        38,000    Diesel
1166  2016            Audi Q3 35 TDI Quattro Premium        75,200    Diesel
1167  2022  Skoda Kushaq 1.5 TSI Style 4 Airbags DSG        36,500    Petrol
1168  2017                Audi A3 cabriolet 1.4 TFSI        49,000    Petrol

     Transmission Price (Lakh)                  Location
0          Manual         5.25        Chromepet, Chennai
1       Automatic           55  Thygaraya Nagar, Chennai
2       Automatic         5.06       Vadapalani, Chennai
3          Manual         5.10     Meenambakkam, Chennai
4       Automatic         5.50                   Chennai
...           ...          ...                       ...
1164    Automatic        18.50           Paltra, Gurgaon
1165    Automatic        15.90           Paltra, Gurgaon
1166    Automatic        12.50           Paltra, Gurgaon
1167    Automatic        12.50           Paltra, Gurgaon
1168    Automatic        37.80           Paltra, Gurgaon

[1169 rows x 7 columns]

In [7]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument("--start-maximized")  # Opens browser in full screen
chrome_options.add_argument("--disable-blink-features=AutomationControlled")  # Avoids detection

driver = webdriver.Chrome(options=chrome_options)  # Initialize browser
driver.get('https://www.cardekho.com/used-cars+in+Hyderabad')
time.sleep(5)  # Wait for page to fully load

last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial height

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")  # Scroll to bottom
    time.sleep(5)  # Wait for new data to load

    new_height = driver.execute_script("return document.body.scrollHeight")  # Get new height

    if new_height == last_height:  # If no new content, break loop
        break
    last_height = new_height

cars = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

structured_data = []

for car in cars:
    try:
        details = car.text.split("\n")  # Split details by line breaks
        
        # Extract Year and Car Name
        year_and_name = details[0].split(" ", 1)
        year = year_and_name[0]
        car_name = year_and_name[1] if len(year_and_name) > 1 else "N/A"

        # Extract Mileage, Fuel Type, Transmission
        mileage = fuel_type = transmission = ""
        if len(details) > 1 and "•" in details[1]:
            specs = [x.strip() for x in details[1].split("•")]
            mileage = specs[0].replace("kms", "").strip() if len(specs) > 0 else ""
            fuel_type = specs[1] if len(specs) > 1 else ""
            transmission = specs[2] if len(specs) > 2 else ""

        # Extract Price
        price = details[2].replace("₹", "").replace("Lakh", "").strip() if len(details) > 2 else "N/A"

        # Extract Location
        location = details[-1] if len(details) > 3 else "N/A"

        # Append extracted data
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })

    except Exception as e:
        print(f"Error processing car details: {details}\nError: {e}")

driver.quit()  # Close browser

# Convert to DataFrame
car_df = pd.DataFrame(structured_data)

# Save as CSV
car_df.to_csv('Hyderabad_car_details.csv', index=False)

# Display DataFrame & Count
print(car_df)

      Year                                           Car Name Mileage (kms)  \
0     2016                              Maruti Swift VDI BSIV        81,562
1     2023  Land Rover Range Rover Sport 3.0 Diesel Dynami...         8,436
2     2024                             BMW X5 xDrive40i xLine         1,913
3     2023                       Audi Q8 55 TFSI Quattro BSVI        30,553
4     2019             Ford Ecosport 1.5 Diesel Titanium BSIV      1,28,542
...    ...                                                ...           ...
1815  2008                            Tata Indica V2 DL BSIII      1,60,000
1816  2021                                   Maruti Swift VXI        30,000
1817  2009                    Tata Manza Aura (ABS) Quadrajet        60,000
1818  2017                  Mahindra XUV500 AT W10 1.99 mHawk        90,000
1819  2019                         Maruti Ignis 1.2 Zeta BSIV        50,000

     Fuel Type Transmission Price (Lakh)             Location
0       Diesel       Manual         5.30     Nagol, Hyderabad
1       Diesel    Automatic   1.65 Crore  Madhapur, Hyderabad
2       Petrol    Automatic   1.16 Crore  Madhapur, Hyderabad
3       Petrol    Automatic   1.05 Crore  Madhapur, Hyderabad
4       Diesel       Manual         7.95     Nagol, Hyderabad
...        ...          ...          ...                  ...
1815    Diesel       Manual       90,000            Hyderabad
1816    Petrol       Manual         5.90            Hyderabad
1817    Diesel       Manual         1.42            Hyderabad
1818    Diesel    Automatic           10            Hyderabad
1819    Petrol       Manual         4.60            Hyderabad

[1820 rows x 7 columns]

In [8]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument("--start-maximized")  # Opens browser in full screen
chrome_options.add_argument("--disable-blink-features=AutomationControlled")  # Avoids detection

driver = webdriver.Chrome(options=chrome_options)  # Initialize browser
driver.get('https://www.cardekho.com/used-cars+in+Mumbai')
time.sleep(5)  # Wait for page to fully load

last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial height

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")  # Scroll to bottom
    time.sleep(5)  # Wait for new data to load

    new_height = driver.execute_script("return document.body.scrollHeight")  # Get new height

    if new_height == last_height:  # If no new content, break loop
        break
    last_height = new_height

cars = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

structured_data = []

for car in cars:
    try:
        details = car.text.split("\n")  # Split details by line breaks
        
        # Extract Year and Car Name
        year_and_name = details[0].split(" ", 1)
        year = year_and_name[0]
        car_name = year_and_name[1] if len(year_and_name) > 1 else "N/A"

        # Extract Mileage, Fuel Type, Transmission
        mileage = fuel_type = transmission = ""
        if len(details) > 1 and "•" in details[1]:
            specs = [x.strip() for x in details[1].split("•")]
            mileage = specs[0].replace("kms", "").strip() if len(specs) > 0 else ""
            fuel_type = specs[1] if len(specs) > 1 else ""
            transmission = specs[2] if len(specs) > 2 else ""

        # Extract Price
        price = details[2].replace("₹", "").replace("Lakh", "").strip() if len(details) > 2 else "N/A"

        # Extract Location
        location = details[-1] if len(details) > 3 else "N/A"

        # Append extracted data
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })

    except Exception as e:
        print(f"Error processing car details: {details}\nError: {e}")

driver.quit()  # Close browser

# Convert to DataFrame
car_df = pd.DataFrame(structured_data)

# Save as CSV
car_df.to_csv('Mumbai_car_details.csv', index=False)

# Display DataFrame & Count
print(car_df)

      Year                         Car Name Mileage (kms) Fuel Type  \
0     2017             Honda Brio 1.2 VX AT        67,000    Petrol
1     2023      Mercedes-Benz GLE 300d BSVI         6,800    Diesel
2     2024          Kia Sonet HTX Diesel AT         5,900    Diesel
3     2021      Mercedes-Benz GLE 300d BSVI        26,500    Diesel
4     2015  Mercedes-Benz C-Class C 200 CGI        71,000    Petrol
...    ...                              ...           ...       ...
1855  2015                Maruti Ertiga VXI        47,238    Petrol
1856  2019                    Honda Jazz VX        42,176    Petrol
1857  2016                  Honda City V MT        56,779    Petrol
1858  2018       Maruti Swift Dzire AMT ZDI        65,000    Diesel
1859  2017         Maruti Vitara Brezza ZDi        80,000    Diesel

     Transmission Price (Lakh)                     Location
0       Automatic         4.99        Borivali West, Mumbai
1       Automatic        94.95         Goregaon (w), Mumbai
2       Automatic        14.75         Goregaon (w), Mumbai
3       Automatic           75          Mulund West, Mumbai
4       Automatic        16.50  Vileparle(west) S.o, Mumbai
...           ...          ...                          ...
1855       Manual         6.59                  West, Thane
1856       Manual         5.91                 Navi, Mumbai
1857       Manual         4.65       Ghatkopar West, Mumbai
1858    Automatic         6.40                 Vadpe, Thane
1859       Manual         7.49      Jogeshwari East, Mumbai

[1860 rows x 7 columns]

In [9]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument("--start-maximized")  # Opens browser in full screen
chrome_options.add_argument("--disable-blink-features=AutomationControlled")  # Avoids detection

driver = webdriver.Chrome(options=chrome_options)  # Initialize browser
driver.get('https://www.cardekho.com/used-cars+in+Ahmedabad')
time.sleep(5)  # Wait for page to fully load

last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial height

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")  # Scroll to bottom
    time.sleep(5)  # Wait for new data to load

    new_height = driver.execute_script("return document.body.scrollHeight")  # Get new height

    if new_height == last_height:  # If no new content, break loop
        break
    last_height = new_height

cars = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

structured_data = []

for car in cars:
    try:
        details = car.text.split("\n")  # Split details by line breaks
        
        # Extract Year and Car Name
        year_and_name = details[0].split(" ", 1)
        year = year_and_name[0]
        car_name = year_and_name[1] if len(year_and_name) > 1 else "N/A"

        # Extract Mileage, Fuel Type, Transmission
        mileage = fuel_type = transmission = ""
        if len(details) > 1 and "•" in details[1]:
            specs = [x.strip() for x in details[1].split("•")]
            mileage = specs[0].replace("kms", "").strip() if len(specs) > 0 else ""
            fuel_type = specs[1] if len(specs) > 1 else ""
            transmission = specs[2] if len(specs) > 2 else ""

        # Extract Price
        price = details[2].replace("₹", "").replace("Lakh", "").strip() if len(details) > 2 else "N/A"

        # Extract Location
        location = details[-1] if len(details) > 3 else "N/A"

        # Append extracted data
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })

    except Exception as e:
        print(f"Error processing car details: {details}\nError: {e}")

driver.quit()  # Close browser

# Convert to DataFrame
car_df = pd.DataFrame(structured_data)

# Save as CSV
car_df.to_csv('Ahmedabad_car_details.csv', index=False)

# Display DataFrame & Count
print(car_df)

      Year                                    Car Name Mileage (kms)  \
0     2023                    BMW X1 sDrive18d M Sport        20,000
1     2022                          Maruti Celerio ZXI        20,280
2     2011                       Hyundai i10 Sportz AT        47,000
3     2012                   Hyundai i20 Sportz AT 1.4        51,000
4     2020                     Kia Sonet HTK Plus BSVI        34,000
...    ...                                         ...           ...
1316  2017                       Mercedes-Benz GLC 220        69,000
1317  2016  Mercedes-Benz C-Class C 200 CGI Avantgarde        66,000
1318  2017             Mercedes-Benz CLA 200 CDI Sport        48,000
1319  2017                       Mercedes-Benz GLC 220        70,000
1320  2014             Mercedes-Benz E-Class E 200 CGI        58,000

     Fuel Type Transmission Price (Lakh)                Location
0       Diesel    Automatic           50               Ahmedabad
1       Petrol       Manual         4.60       Naroda, Ahmedabad
2       Petrol    Automatic            3  Navrangpura, Ahmedabad
3       Petrol    Automatic         3.25  Navrangpura, Ahmedabad
4       Petrol       Manual         8.50      Abasana, Ahmedabad
...        ...          ...          ...                     ...
1316    Diesel    Automatic        33.90   Chattarpur, New Delhi
1317    Petrol    Automatic        25.90   Chattarpur, New Delhi
1318    Diesel    Automatic        20.90   Chattarpur, New Delhi
1319    Diesel    Automatic        33.90   Chattarpur, New Delhi
1320    Petrol    Automatic        18.90   Chattarpur, New Delhi

[1321 rows x 7 columns]

In [10]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument("--start-maximized")  # Opens browser in full screen
chrome_options.add_argument("--disable-blink-features=AutomationControlled")  # Avoids detection

driver = webdriver.Chrome(options=chrome_options)  # Initialize browser
driver.get('https://www.cardekho.com/used-cars+in+Delhi NCR')
time.sleep(5)  # Wait for page to fully load

last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial height

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")  # Scroll to bottom
    time.sleep(5)  # Wait for new data to load

    new_height = driver.execute_script("return document.body.scrollHeight")  # Get new height

    if new_height == last_height:  # If no new content, break loop
        break
    last_height = new_height

cars = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

structured_data = []

for car in cars:
    try:
        details = car.text.split("\n")  # Split details by line breaks
        
        # Extract Year and Car Name
        year_and_name = details[0].split(" ", 1)
        year = year_and_name[0]
        car_name = year_and_name[1] if len(year_and_name) > 1 else "N/A"

        # Extract Mileage, Fuel Type, Transmission
        mileage = fuel_type = transmission = ""
        if len(details) > 1 and "•" in details[1]:
            specs = [x.strip() for x in details[1].split("•")]
            mileage = specs[0].replace("kms", "").strip() if len(specs) > 0 else ""
            fuel_type = specs[1] if len(specs) > 1 else ""
            transmission = specs[2] if len(specs) > 2 else ""

        # Extract Price
        price = details[2].replace("₹", "").replace("Lakh", "").strip() if len(details) > 2 else "N/A"

        # Extract Location
        location = details[-1] if len(details) > 3 else "N/A"

        # Append extracted data
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })

    except Exception as e:
        print(f"Error processing car details: {details}\nError: {e}")

driver.quit()  # Close browser

# Convert to DataFrame
car_df = pd.DataFrame(structured_data)

# Save as CSV
car_df.to_csv('Delhi_NCR_car_details.csv', index=False)

# Display DataFrame & Count
print(car_df)

      Year                                 Car Name Mileage (kms) Fuel Type  \
0       AD                                      N/A
1     2022                  Renault Triber RXL BSVI        32,000    Petrol
2     2024            Jaguar F-Pace 2.0 R-Dynamic S         6,000    Petrol
3     2024             Audi Q7 Technology WO Matrix         5,000    Petrol
4     2021                        Renault Kiger RXT        12,000    Petrol
...    ...                                      ...           ...       ...
2115  2022   Volkswagen Taigun 1.0 TSI Topline BSVI        17,170    Petrol
2116  2018  Hyundai Grand i10 1.2 Kappa Sportz BSIV        64,642    Petrol
2117  2019     Hyundai Venue SX Plus Turbo DCT BSIV        46,000    Petrol
2118  2018         Land Rover Discovery HSE 3.0 TD6        59,800    Diesel
2119  2011                      Toyota Etios Liva G        48,132    Petrol

     Transmission                             Price (Lakh)  \
0                  39,409 kms   •   Diesel   •   Automatic
1          Manual                                     5.25
2       Automatic                                       68
3       Automatic                                    86.90
4          Manual                                     5.45
...           ...                                      ...
2115       Manual                                    12.71
2116       Manual                                     4.24
2117    Automatic                                     8.40
2118    Automatic                                       28
2119       Manual                                     2.07

                      Location
0          Sector 21e, Gurgaon
1      Ramesh Nagar, New Delhi
2                      Gurgaon
3              Paltra, Gurgaon
4               Badli, Gurgaon
...                        ...
2115        Sector 28, Gurgaon
2116  Rohini Courts, New Delhi
2117    Ashok Nagar, New Delhi
2118      Janakpuri, New Delhi
2119    Indirapuram, Ghaziabad

[2120 rows x 7 columns]

In [11]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument("--start-maximized")  # Opens browser in full screen
chrome_options.add_argument("--disable-blink-features=AutomationControlled")  # Avoids detection

driver = webdriver.Chrome(options=chrome_options)  # Initialize browser
driver.get('https://www.cardekho.com/used-cars+in+Kolkata')
time.sleep(5)  # Wait for page to fully load

last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial height

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")  # Scroll to bottom
    time.sleep(5)  # Wait for new data to load

    new_height = driver.execute_script("return document.body.scrollHeight")  # Get new height

    if new_height == last_height:  # If no new content, break loop
        break
    last_height = new_height

cars = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

structured_data = []

for car in cars:
    try:
        details = car.text.split("\n")  # Split details by line breaks
        
        # Extract Year and Car Name
        year_and_name = details[0].split(" ", 1)
        year = year_and_name[0]
        car_name = year_and_name[1] if len(year_and_name) > 1 else "N/A"

        # Extract Mileage, Fuel Type, Transmission
        mileage = fuel_type = transmission = ""
        if len(details) > 1 and "•" in details[1]:
            specs = [x.strip() for x in details[1].split("•")]
            mileage = specs[0].replace("kms", "").strip() if len(specs) > 0 else ""
            fuel_type = specs[1] if len(specs) > 1 else ""
            transmission = specs[2] if len(specs) > 2 else ""

        # Extract Price
        price = details[2].replace("₹", "").replace("Lakh", "").strip() if len(details) > 2 else "N/A"

        # Extract Location
        location = details[-1] if len(details) > 3 else "N/A"

        # Append extracted data
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })

    except Exception as e:
        print(f"Error processing car details: {details}\nError: {e}")

driver.quit()  # Close browser

# Convert to DataFrame
car_df = pd.DataFrame(structured_data)

# Save as CSV
car_df.to_csv('Kolkata_car_details.csv', index=False)

# Display DataFrame & Count
print(car_df)

      Year                       Car Name Mileage (kms) Fuel Type  \
0     2020  Mercedes-Benz GLC 220d 4MATIC        33,041    Diesel
1     2010          Hyundai i20 1.2 Magna        49,000    Petrol
2     2021       Toyota Urban cruiser Mid        20,317    Petrol
3     2021              Renault Kiger RXL        36,758    Petrol
4     2017        Honda BR-V i-VTEC VX MT        27,000    Petrol
...    ...                            ...           ...       ...
1164  2014      Hyundai Xcent 1.2 Kappa S        20,000    Petrol
1165  2012         Maruti Swift Dzire VXI        44,000    Petrol
1166  2008           Hyundai Getz 1.1 GVS        55,000    Petrol
1167  2011         Hyundai Verna 1.4 VTVT        93,000    Petrol
1168  2019   Maruti Eeco 5 Seater AC BSIV        40,000    Petrol

     Transmission Price (Lakh)                                Location
0       Automatic           38                  Vaishya Sabha, Kolkata
1          Manual         1.30                     Airport Po, Kolkata
2          Manual         6.80                     University, Kolkata
3          Manual         4.50                        Alipore, Kolkata
4          Manual         6.65                          Kasba, Kolkata
...           ...          ...                                     ...
1164       Manual         2.75  Paschim Rameswarpur, North 24 Parganas
1165       Manual         2.50  Paschim Rameswarpur, North 24 Parganas
1166       Manual         1.05  Paschim Rameswarpur, North 24 Parganas
1167       Manual         2.10  Paschim Rameswarpur, North 24 Parganas
1168       Manual         3.60  Paschim Rameswarpur, North 24 Parganas

[1169 rows x 7 columns]